examples/organization-viewer-cli/src/index.ts, packages/connect-thegraph/package.json, packages/connect-thegraph/src/core/GraphQLWrapper.ts, yarn.lock
This PR implements the low level `subscribeToQuery(...)` function in **connect-thegraph/src/core/GraphQLWrapper.ts**.
See ` inspectVotingLowLevelSubscription(...)` in **examples/organization-viewer-cli/src/index.ts** for usage.
If a vote is created in the org while the demo is running, you will see it pop up in the demo's stdout.
_Note_: Next steps regarding subscriptions is to actually use this low level function in the connectors. This will probably imply slight modifications to how we build gql queries, and an event system that connectors must comply to (`on(...)`, `off(...)`), but not much more than that to have working subscriptions all over.
=> Implements low-level subscriptions in thegraph connectors

examples/organization-viewer-web/src/OrgApps.tsx, examples/organization-viewer-web/src/OrgInfo.tsx, packages/connect-thegraph/package.json, packages/connect-thegraph/src/core/GraphQLWrapper.ts, yarn.lock
- Replaces `ws` with `isomorphic-ws` so subscriptions can work in browsers
- Fixes `Application` name
- Fixes property accessing error in `OrgInfo` and simplify logic. The component was only displaying the address so using `Object.entries()` was not really necessary.
=> Fix web example

packages/connect-thegraph/src/core/GraphQLWrapper.ts
From version `0.1` to `0.2` we had a behavior change with urql as it now errors silently if it doesn't have an URL to work with, leading the library to throw a very obscure `cannot read property replace of undefined`. This PR detects if there's no URL passed in, or if it's not valid (doesn't contain `http`, as we're assuming this down below for creating subscriptions) and throws an error with a more meaningful description.
We could also start thinking about making our own errors, extending them from the `Error` class, akin to how `web3-react` handles this.
=> TheGraph Connector: Parse subgraph URL in GraphQLWrapper to catch invalid URLs

packages/connect-thegraph/subgraph/manifest/data/xdai-staging.json, packages/connect-thegraph/subgraph/manifest/data/xdai.json, packages/connect/src/connect.ts
1Hive is deploying Aragon Infrastructure to xDai and this is a requirement for `connect` to keep compatible with it.
=> Add support for xdai network

docs/api-reference/app.md, docs/api-reference/connect.md, docs/api-reference/connectors.md, docs/api-reference/organization.md, docs/api-reference/permission.md, docs/api-reference/repo.md, docs/api-reference/role.md, packages/connect-core/src/entities/Application.ts, packages/connect-core/src/entities/Repository.ts, packages/connect-core/src/entities/Role.ts, packages/connect-core/src/utils/path/calculatePath.ts, packages/connect-ethereum/README.md, packages/connect-thegraph/README.md, packages/connect-thegraph/src/__test__/apps.test.ts, packages/connect-thegraph/src/__test__/roles.test.ts, packages/connect-thegraph/src/parsers/repos.ts
Note I did a first commit where I included lint to the markdown files. The actual documentation changes are on this commit: https://github.com/aragon/connect/pull/72/commits/3a32151a41b0acf3b18802c26dd19fd678178588
=> Docs review

docs/api-reference/organization.md, examples/nodejs/src/organization.ts, examples/org-viewer-web/src/OrgApps.tsx, packages/connect-core/src/entities/Organization.ts, packages/connect-core/src/types.ts, packages/connect-core/src/utils/app.ts, packages/connect-thegraph/src/connector.ts, packages/connect-thegraph/src/parsers/apps.ts
Adding a few more things to the PR:
- Move examples to use `App`.
- Update some comments and formatting.
- Update the TODO in Organization.ts
- [Improve a callback type](https://github.com/aragon/connect/compare/rename-app-and-repo...rename-app-and-repo-more?expand=1#diff-da82e438aa17d498b7f7c1350529ed4cR89) (this one doesn’t really belong here but is really minor, let me know if you prefer to remove it).
=> Add a few more things to the PR “Renamed App and Repo”

docs/api-reference/organization.md, examples/nodejs/src/organization.ts, examples/nodejs/src/transaction-path.ts, examples/org-viewer-web/src/OrgApps.tsx, packages/connect-core/src/connections/ConnectorInterface.ts, packages/connect-core/src/connections/ConnectorJson.ts, packages/connect-core/src/entities/App.ts, packages/connect-core/src/entities/Organization.ts, packages/connect-core/src/entities/Permission.ts, packages/connect-core/src/entities/Repo.ts, packages/connect-core/src/index.ts, packages/connect-core/src/transactions/TransactionIntent.ts, packages/connect-core/src/transactions/TransactionPath.ts, packages/connect-core/src/types.ts, packages/connect-core/src/utils/app.ts, packages/connect-core/src/utils/path/calculatePath.ts, packages/connect-core/src/utils/path/describePath.ts, packages/connect-core/src/utils/radspec/index.ts, packages/connect-core/src/utils/radspec/postprocess.ts, packages/connect-core/src/utils/transactions.ts, packages/connect-ethereum/src/index.ts, packages/connect-thegraph/src/__test__/apps.test.ts, packages/connect-thegraph/src/__test__/repos.test.ts, packages/connect-thegraph/src/connector.ts, packages/connect-thegraph/src/parsers/apps.ts, packages/connect-thegraph/src/parsers/repos.ts
As discussed, this PR applies the following names on the core entities:
* Organization
* Application => App
* Repository => Repo
* Role
* Permission
=> Renamed App and Repo

packages/connect-core/src/entities/App.ts, packages/connect-core/src/utils/app.ts, packages/connect-core/src/utils/overrides/abi/ACL.json, packages/connect-core/src/utils/overrides/abi/APMRegistry.json, packages/connect-core/src/utils/overrides/abi/ENSSubdomainRegistrar.json, packages/connect-core/src/utils/overrides/abi/EVMScriptRegistry.json, packages/connect-core/src/utils/overrides/abi/Kernel.json, packages/connect-core/src/utils/overrides/abi/Repo.json, packages/connect-core/src/utils/overrides/artifacts/apm/APMRegistry.json, packages/connect-core/src/utils/overrides/artifacts/apm/ENSSubdomainRegistrar.json, packages/connect-core/src/utils/overrides/artifacts/apm/Repo.json, packages/connect-core/src/utils/overrides/artifacts/aragon/ACL.json, packages/connect-core/src/utils/overrides/artifacts/aragon/EVMScriptRegistry.json, packages/connect-core/src/utils/overrides/artifacts/aragon/Kernel.json, packages/connect-core/src/utils/overrides/index.ts, packages/connect-core/src/utils/overrides/interfaces.ts, packages/connect-core/tsconfig.json
Includes manual override of the artifact metadata for apps without an aragonPM repo:
- Kernel
- ACL
- EVM Script Registry
- Repo
- APM Registry
- ENS Subdomain Registrar
=> Feat: Add overrides for apps without aragonPM repos

docs/api-reference/connect.md, docs/guides/connect-with-react.md
@bpierre I wonder if maybe we should use `or` as we did in a few places.
=> Docs: Use \| as separators

packages/connect-core/src/entities/Organization.ts, packages/connect-core/src/params.ts, packages/connect-thegraph/src/connector.ts
This PR adds support for `xDai` default provider and subgraph URL.
Until now users need to use the library like: 
```tsx
const provider = new ethers.providers.JsonRpcProvider(
'https://xdai.poanetwork.dev',
{
name: 'xdai',
chainId: 100,
ensAddress: '0xaafca6b0c89521752e559650206d7c925fd0e530',
}
)
const org = await connect(
daoAddress,
[
'thegraph',
{ orgSubgraphUrl: 'https://api.thegraph.com/subgraphs/name/1hive/aragon-xdai' },
],
{ chainId: 100, readProvider: ethereum }
)
```
With this change we can do:
```tsx
const org = await connect(ORG_ADDRESS, 'thegraph', {
chainId: 100,
})
```
=> Feat: Support xDai network provider and subgraph url

packages/connect-thegraph/src/__test__/roles.test.ts, packages/connect-thegraph/src/parsers/roles.ts, packages/connect-thegraph/src/queries/index.ts
Fix an issue during the creation of the `Repo` entity. When there is no artifact metadata on the subgraph available we try to manually fetch it using the `contentUri` attribute. With the changes made in the latest version (https://github.com/aragon/connect/pull/121), we introduced a regression bug pointing to the wrong data: `app.contentUri` -> `app.version.contentUri`.
=> Fix: Add appId to repo query + fix typo on argument

packages/connect-core/src/entities/App.ts, packages/connect-core/src/entities/Repo.ts, packages/connect-core/src/utils/metadata.ts
Also remove unnecessary `undefined` assignments.
=> Types: remove some non-null assertion operators (!)

docs/api-reference/organization.md, docs/connectors/organizations.md, packages/connect-core/src/connections/ConnectorInterface.ts, packages/connect-core/src/connections/ConnectorJson.ts, packages/connect-core/src/entities/Organization.ts, packages/connect-core/src/types.ts, packages/connect-ethereum/src/index.ts, packages/connect-react/src/index.ts, packages/connect-thegraph-tokens/src/connector.ts, packages/connect-thegraph-tokens/src/entities/Token.ts, packages/connect-thegraph-voting/src/connector.ts, packages/connect-thegraph-voting/src/entities/Vote.ts, packages/connect-thegraph-voting/src/entities/Voting.ts, packages/connect-thegraph-voting/src/entities/VotingEntity.ts, packages/connect-thegraph/src/connector.ts, packages/connect-thegraph/src/core/GraphQLWrapper.ts, packages/connect-types/src/index.ts
Extracting some changes out of https://github.com/aragon/connect/pull/135 to make it easier to review.
=> Types: add SubscriptionHandler, Address

packages/connect-core/src/connections/ConnectorJson.ts, packages/connect-core/src/connections/IOrganizationConnector.ts, packages/connect-core/src/entities/App.ts, packages/connect-core/src/entities/CoreEntity.ts, packages/connect-core/src/entities/Organization.ts, packages/connect-core/src/entities/Permission.ts, packages/connect-core/src/entities/Repo.ts, packages/connect-core/src/entities/Role.ts, packages/connect-core/src/index.ts, packages/connect-core/src/types.ts, packages/connect-ethereum/src/index.ts, packages/connect-thegraph/src/__test__/apps.test.ts, packages/connect-thegraph/src/__test__/permissions.test.ts, packages/connect-thegraph/src/__test__/repos.test.ts, packages/connect-thegraph/src/__test__/roles.test.ts, packages/connect-thegraph/src/connector.ts, packages/connect-thegraph/src/parsers/apps.ts, packages/connect-thegraph/src/parsers/permissions.ts, packages/connect/src/connect.ts
It also now contains the `name` and `network` properties.
=> Rename ConnectorInterface to IOrganizationConnector

packages/connect-thegraph/subgraph/schema.graphql, packages/connect-thegraph/subgraph/src/mappings/organization.ts, packages/connect-thegraph/subgraph/src/mappings/registry.ts
This commit adds a metric that signifies the number of times an app has been installed.
I couldn't find a nice way to have a single "global" entity that could serve as a container for global metrics such as an overall organization count, so I opted to not implement that and resort to summing the `orgCount` properties of each organization factory in Apiary. If you have another idea I'd be glad to hear it 👍 
Closes #139
=> Add app installation count to `Repo` entity

packages/connect-agreement/package.json, packages/connect-voting-disputable/package.json
The `private` field will be removed whenever we feel their API is stable enough.
Also moved to fixed version ranges for the Connect packages.
=> Mark voting-disputable and agreements as private packages

packages/connect-agreement/subgraph/manifest/data/xdai.json, packages/connect-agreement/subgraph/package.json, packages/connect-voting-disputable/subgraph/manifest/data/xdai.json, packages/connect-voting-disputable/subgraph/package.json
Changes to the deployment manifest data. 
The official subgraphs were deployed from the Aragon account for Agreements and Disputable Voting apps.
=> Subgraph: Update subgraph deployments

packages/connect-core/src/utils/app-connectors.ts
The app instance passed to `createAppConnector()` might come from the a version of `@aragon/connect-core` that is a dependent of `@aragon/connect`, which is generally included as a direct dependency by the final app.
`createAppConnector()` itself comes from the app connector package, which might contain a different version of `@aragon/connect-core`.
These situations make the use of `typeof` impossible, as two `App` constructors would come from the two different modules.
There are also other situations where linking one dependency (e.g. the app connector only) can create the same issue.
This commits moves to duck typing to validate the App instance, which also make it work in these different scenarios.
=> createAppConnector(): stop using instanceof

examples/bundler-parcel/.gitignore, examples/bundler-parcel/package.json, examples/bundler-parcel/src/index.html, examples/bundler-parcel/src/index.js, examples/bundler-webpack-ts-loader/package.json, examples/bundler-webpack-ts-loader/src/index.html, examples/bundler-webpack-ts-loader/src/index.tsx, examples/bundler-webpack-ts-loader/tsconfig.json, examples/bundler-webpack-ts-loader/webpack.config.js, examples/list-balances-cli/src/index.ts, examples/list-votes-cli/src/index.ts, examples/minimal-setup-web/index.html, examples/minimal-setup-web/package.json, examples/org-viewer-react/package.json, examples/org-viewer-react/src/App.tsx, examples/org-viewer-react/src/environment.ts, examples/org-viewer-react/webpack.config.js, examples/org-viewer-web/package.json, examples/org-viewer-web/src/App.tsx, examples/org-viewer-web/src/environment.ts, examples/org-viewer-web/webpack.config.js, yarn.lock
Three main things:
- Move from webpack 5 to webpack 4 (webpack 5 is having some issues with ethers at the moment).
- Add bundler-specific demos (Parcel and Webpack with ts-loader).
- Use latest Connect APIs.
=> Examples cleanup

packages/connect-thegraph/src/connector.ts
Reverting [this change](https://github.com/aragon/connect/pull/229/commits/19dbea4ed58f16d66c68081bda841f8bfd304bcf) as it breaks the connector.
=> Fix onAppForOrg()

packages/connect-agreement/package.json, packages/connect-core/package.json, packages/connect-core/src/transactions/TransactionIntent.ts, packages/connect-core/src/types.ts, packages/connect-core/src/utils/app.ts, packages/connect-core/src/utils/callScript.ts, packages/connect-core/src/utils/descriptions.ts, packages/connect-core/src/utils/forwarding.ts, packages/connect-core/src/utils/kernel.ts, packages/connect-core/src/utils/metadata.ts, packages/connect-core/src/utils/path/calculatePath.ts, packages/connect-core/src/utils/radspec/index.ts, packages/connect-core/src/utils/transactions.ts, packages/connect-ethereum/package.json, packages/connect-finance/package.json, packages/connect-react/package.json, packages/connect-thegraph/package.json, packages/connect-tokens/package.json, packages/connect-voting-disputable/package.json, packages/connect-voting/package.json, packages/connect/package.json, packages/connect/src/connect.ts
This doesn’t change much at the moment ([see issue on the ethers.js repo](https://github.com/ethers-io/ethers.js/issues/1009)), but will make it possible to tree shake Ethers in the future.
=> Ethers: use named imports

packages/connect-voting-disputable/src/models/Vote.ts, packages/connect-voting-disputable/src/thegraph/connector.ts, packages/connect-voting-disputable/src/thegraph/parsers/collateralRequirements.ts
Fix CI adding missing SubscriptionCallback + update collateralRequirement tokenId
=> Fix: Add missing SubscriptionCallback types

packages/connect-finance/src/models/Finance.ts, packages/connect-finance/src/thegraph/connector.ts, packages/connect-finance/src/types.ts, packages/connect-tokens/src/connect.ts, packages/connect-tokens/src/models/Tokens.ts, packages/connect-tokens/src/thegraph/connector.ts, packages/connect-tokens/src/types.ts, packages/connect-voting/src/models/Vote.ts, packages/connect-voting/src/models/Voting.ts, packages/connect-voting/src/thegraph/connector.ts, packages/connect-voting/src/types.ts
This PR aligns the subscription methods with their async counterparts for the Finance, Voting and Tokens app connectors.
It is a breaking change.
=> App connectors: align subscription methods

packages/connect-core/package.json, packages/connect-disputable-voting/src/__test__/thegraph/votes.test.ts, yarn.lock
Bump the current radspec version to include the latest available descriptions.
=> Dependency: Bump radspec version

docs/guides/getting-started.md
The current version of Connect returns the whole list of Transactions on the Forwarding Path so the example:
```
for (const transaction of path.transactions) {
await ethers.sendTransaction(transaction)
}
```
Don't work as expected. In the current refactor #256 we address this issue.
=> Docs: fix intent async method + remove miss-leading example

packages/connect-agreement/src/connect.ts, packages/connect-agreement/src/thegraph/connector.ts, packages/connect-agreement/src/thegraph/parsers/agreement.ts
- Custom errors.
- Uses `AgreementConnectorTheGraph.create()` to instantiate.
- Use `Address` when possible.
=> Agreement: align the connector with the other app connectors

examples/bundler-parcel/package.json, examples/bundler-webpack-ts-loader/package.json, examples/connect-react-intro/package.json, examples/list-balances-cli/package.json, examples/list-votes-cli/package.json, examples/list-votes-react/package.json, examples/minimal-setup-web/package.json, examples/nodejs/package.json, examples/org-viewer-react/package.json, examples/org-viewer-web/package.json, package.json, packages/connect-agreement/package.json, packages/connect-core/package.json, packages/connect-core/src/utils/app.ts, packages/connect-core/src/utils/intent.ts, packages/connect-disputable-voting/package.json, packages/connect-ethereum/package.json, packages/connect-finance/package.json, packages/connect-react/package.json, packages/connect-thegraph/package.json, packages/connect-tokens/package.json, packages/connect-types/package.json, packages/connect-voting/package.json, packages/connect-voting/subgraph/manifest/data/mainnet-staging.json, packages/connect-voting/subgraph/manifest/data/rinkeby-staging.json, packages/connect-voting/subgraph/schema.graphql, packages/connect-voting/subgraph/src/Voting.ts, packages/connect/package.json
Reuse changes from https://github.com/aragon/aragon-cli/pull/1687
This fix prevents using the wrong signature hash from artifact functions by preferring creating the signature from the ABI definition.
=> Core: prefer generating signature from ABI
